### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by andmetoo** [design-pattern-ru/design-pattern-ru.github.io#2]
Паттерн Singleton , один из самых важных, нужно добавить его в первую очередь

https://ru.wikipedia.org/wiki/Одиночка_(шаблон_проектирования)

**Comment by coyl** [comment]
Паттерн важный, потому что спорный, я – за. Если сделаете PR, буду очень благодарен.

**Comment by samizdam** [comment]
#3 если нужна диаграмма, то вопрос — в какой туле созданы остальные? Чтобы единообразно было.

**Comment by samizdam** [comment]
Up.

**Comment by coyl** [comment]
Sorry, can't take a look right now. I'm on my vacations.
